export const CREATE_ACCOUNT_TYPE_REQUEST = "CREATE_ACCOUNT_TYPE_REQUEST";
export const CREATE_ACCOUNT_TYPE_SUCCESS = "  CREATE_ACCOUNT_TYPE_SUCCESS";
export const CREATE_ACCOUNT_TYPE_FAILURE = "  CREATE_ACCOUNT_TYPE_FAILURE";
export const FETCH_ACCOUNT_TYPES_REQUEST = "  FETCH_ACCOUNT_TYPES_REQUEST";
export const FETCH_ACCOUNT_TYPES_SUCCESS = "  FETCH_ACCOUNT_TYPES_SUCCESS";
export const FETCH_ACCOUNT_TYPES_FAILURE = "  FETCH_ACCOUNT_TYPES_FAILURE";
export const GET_ACCOUNT_TYPE_DETAILS_REQUEST =
  "  GET_ACCOUNT_TYPE_DETAILS_REQUEST";
export const GET_ACCOUNT_TYPE_DETAILS_SUCCESS =
  "  GET_ACCOUNT_TYPE_DETAILS_SUCCESS";
export const GET_ACCOUNT_TYPE_DETAILS_FAILURE =
  "  GET_ACCOUNT_TYPE_DETAILS_FAILURE";
export const UPDATE_ACCOUNT_TYPE_REQUEST = "  UPDATE_ACCOUNT_TYPE_REQUEST";
export const UPDATE_ACCOUNT_TYPE_SUCCESS = "  UPDATE_ACCOUNT_TYPE_SUCCESS";
export const UPDATE_ACCOUNT_TYPE_FAILURE = "  UPDATE_ACCOUNT_TYPE_FAILURE";
export const DELETE_ACCOUNT_TYPE_REQUEST = "  DELETE_ACCOUNT_TYPE_REQUEST";
export const DELETE_ACCOUNT_TYPE_SUCCESS = "  DELETE_ACCOUNT_TYPE_SUCCESS";
export const DELETE_ACCOUNT_TYPE_FAILUR = "  DELETE_ACCOUNT_TYPE_FAILURE";
