export const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST";
export const CREATE_ACCOUNT_SUCCESS = "  CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "  CREATE_ACCOUNT_FAILURE";
export const FETCH_ACCOUNTS_REQUEST = "  FETCH_ACCOUNTS_REQUEST";
export const FETCH_ACCOUNTS_SUCCESS = "  FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAILURE = "  FETCH_ACCOUNTS_FAILURE";
export const GET_ACCOUNT_DETAILS_REQUEST = "  GET_ACCOUNT_DETAILS_REQUEST";
export const GET_ACCOUNT_DETAILS_SUCCESS = "  GET_ACCOUNT_DETAILS_SUCCESS";
export const GET_ACCOUNT_DETAILS_FAILURE = "  GET_ACCOUNT_DETAILS_FAILURE";
export const UPDATE_ACCOUNT_BALANCE_REQUEST =
  "  UPDATE_ACCOUNT_BALANCE_REQUEST";
export const UPDATE_ACCOUNT_BALANCE_SUCCESS =
  "  UPDATE_ACCOUNT_BALANCE_SUCCESS";
export const UPDATE_ACCOUNT_BALANCE_FAILURE =
  "  UPDATE_ACCOUNT_BALANCE_FAILURE";
export const DELETE_ACCOUNT_REQUEST = "  DELETE_ACCOUNT_REQUEST";
export const DELETE_ACCOUNT_SUCCESS = "  DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_FAILURE = "  DELETE_ACCOUNT_FAILURE";
