export const FETCH_CASH_TRANSACTIONS_REQUEST =
  "FETCH_CASH_TRANSACTIONS_REQUEST";
export const FETCH_CASH_TRANSACTIONS_SUCCESS =
  "  FETCH_CASH_TRANSACTIONS_SUCCESS";
export const FETCH_CASH_TRANSACTIONS_FAILURE =
  "  FETCH_CASH_TRANSACTIONS_FAILURE";
export const GET_CASH_TRANSACTION_DETAILS_REQUEST =
  "  GET_CASH_TRANSACTION_DETAILS_REQUEST";
export const GET_CASH_TRANSACTION_DETAILS_SUCCESS =
  "  GET_CASH_TRANSACTION_DETAILS_SUCCESS";
export const GET_CASH_TRANSACTION_DETAILS_FAILURE =
  "  GET_CASH_TRANSACTION_DETAILS_FAILURE";
export const CREATE_CASH_TRANSACTION_REQUEST =
  "  CREATE_CASH_TRANSACTION_REQUEST";
export const CREATE_CASH_TRANSACTION_SUCCESS =
  "  CREATE_CASH_TRANSACTION_SUCCESS";
export const CREATE_CASH_TRANSACTION_FAILURE =
  "  CREATE_CASH_TRANSACTION_FAILURE";
export const UPDATE_CASH_TRANSACTION_REQUEST =
  "  UPDATE_CASH_TRANSACTION_REQUEST";
export const UPDATE_CASH_TRANSACTION_SUCCESS =
  "  UPDATE_CASH_TRANSACTION_SUCCESS";
export const UPDATE_CASH_TRANSACTION_FAILURE =
  "  UPDATE_CASH_TRANSACTION_FAILURE";
export const DELETE_CASH_TRANSACTION_REQUEST =
  "  DELETE_CASH_TRANSACTION_REQUEST";
export const DELETE_CASH_TRANSACTION_SUCCESS =
  "  DELETE_CASH_TRANSACTION_SUCCESS";
export const DELETE_CASH_TRANSACTION_FAILURE =
  "  DELETE_CASH_TRANSACTION_FAILURE";
