export const GET_ALL_INTEREST_RATES_REQUEST = "GET_ALL_INTEREST_RATES_REQUEST";
export const GET_ALL_INTEREST_RATES_SUCCESS =
  "  GET_ALL_INTEREST_RATES_SUCCESS";
export const GET_ALL_INTEREST_RATES_FAILURE =
  "  GET_ALL_INTEREST_RATES_FAILURE";
export const GET_INTEREST_RATE_BY_ACCOUNT_TYPE_REQUEST =
  "  GET_INTEREST_RATE_BY_ACCOUNT_TYPE_REQUEST";
export const GET_INTEREST_RATE_BY_ACCOUNT_TYPE_SUCCESS =
  "  GET_INTEREST_RATE_BY_ACCOUNT_TYPE_SUCCESS";
export const GET_INTEREST_RATE_BY_ACCOUNT_TYPE_FAILURE =
  "  GET_INTEREST_RATE_BY_ACCOUNT_TYPE_FAILURE";
export const CREATE_INTEREST_RATE_REQUEST = "  CREATE_INTEREST_RATE_REQUEST";
export const CREATE_INTEREST_RATE_SUCCESS = "  CREATE_INTEREST_RATE_SUCCESS";
export const CREATE_INTEREST_RATE_FAILURE = "  CREATE_INTEREST_RATE_FAILURE";
export const UPDATE_INTEREST_RATE_REQUEST = "  UPDATE_INTEREST_RATE_REQUEST";
export const UPDATE_INTEREST_RATE_SUCCESS = "  UPDATE_INTEREST_RATE_SUCCESS";
export const UPDATE_INTEREST_RATE_FAILURE = "  UPDATE_INTEREST_RATE_FAILURE";
export const DELETE_INTEREST_RATE_REQUEST = "  DELETE_INTEREST_RATE_REQUEST";
export const DELETE_INTEREST_RATE_SUCCESS = "  DELETE_INTEREST_RATE_SUCCESS";
export const DELETE_INTEREST_RATE_FAILURE = "  DELETE_INTEREST_RATE_FAILURE";
