export const CREATE_KYC_DOCUMENT_REQUEST = "CREATE_KYC_DOCUMENT_REQUEST";
export const CREATE_KYC_DOCUMENT_SUCCESS = "  CREATE_KYC_DOCUMENT_SUCCESS";
export const CREATE_KYC_DOCUMENT_FAILURE = "  CREATE_KYC_DOCUMENT_FAILURE";
export const GET_ALL_KYC_DOCUMENTS_REQUEST = "  GET_ALL_KYC_DOCUMENTS_REQUEST";
export const GET_ALL_KYC_DOCUMENTS_SUCCESS = "  GET_ALL_KYC_DOCUMENTS_SUCCESS";
export const GET_ALL_KYC_DOCUMENTS_FAILURE = "  GET_ALL_KYC_DOCUMENTS_FAILURE";
export const GET_KYC_DOCUMENT_BY_ID_REQUEST =
  "  GET_KYC_DOCUMENT_BY_ID_REQUEST";
export const GET_KYC_DOCUMENT_BY_ID_SUCCESS =
  "  GET_KYC_DOCUMENT_BY_ID_SUCCESS";
export const GET_KYC_DOCUMENT_BY_ID_FAILURE =
  "  GET_KYC_DOCUMENT_BY_ID_FAILURE";
export const UPDATE_KYC_DOCUMENT_REQUEST = "  UPDATE_KYC_DOCUMENT_REQUEST";
export const UPDATE_KYC_DOCUMENT_SUCCESS = "  UPDATE_KYC_DOCUMENT_SUCCESS";
export const UPDATE_KYC_DOCUMENT_FAILURE = "  UPDATE_KYC_DOCUMENT_FAILURE";
export const DELETE_KYC_DOCUMENT_REQUEST = "  DELETE_KYC_DOCUMENT_REQUEST";
export const DELETE_KYC_DOCUMENT_SUCCESS = "  DELETE_KYC_DOCUMENT_SUCCESS";
export const DELETE_KYC_DOCUMENT_FAILURE = "  DELETE_KYC_DOCUMENT_FAILURE";
