export const GET_ALL_LOANS_REQUEST = "GET_ALL_LOANS_REQUEST";
export const GET_ALL_LOANS_SUCCESS = "  GET_ALL_LOANS_SUCCESS";
export const GET_ALL_LOANS_FAILURE = "  GET_ALL_LOANS_FAILURE";
export const GET_LOAN_BY_CUSTOMER_ID_REQUEST =
  "  GET_LOAN_BY_CUSTOMER_ID_REQUEST";
export const GET_LOAN_BY_CUSTOMER_ID_SUCCESS =
  "  GET_LOAN_BY_CUSTOMER_ID_SUCCESS";
export const GET_LOAN_BY_CUSTOMER_ID_FAILURE =
  "  GET_LOAN_BY_CUSTOMER_ID_FAILURE";
export const CREATE_LOAN_REQUEST = "  CREATE_LOAN_REQUEST";
export const CREATE_LOAN_SUCCESS = "  CREATE_LOAN_SUCCESS";
export const CREATE_LOAN_FAILURE = "  CREATE_LOAN_FAILURE";
export const UPDATE_LOAN_REQUEST = "  UPDATE_LOAN_REQUEST";
export const UPDATE_LOAN_SUCCESS = "  UPDATE_LOAN_SUCCESS";
export const UPDATE_LOAN_FAILURE = "  UPDATE_LOAN_FAILURE";
export const DELETE_LOAN_REQUEST = "  DELETE_LOAN_REQUEST";
export const DELETE_LOAN_SUCCESS = "  DELETE_LOAN_SUCCESS";
export const DELETE_LOAN_FAILURE = "  DELETE_LOAN_FAILURE";
