export const GET_ALL_NOTIFICATIONS_REQUEST = "GET_ALL_NOTIFICATIONS_REQUEST";
export const GET_ALL_NOTIFICATIONS_SUCCESS = "  GET_ALL_NOTIFICATIONS_SUCCESS";
export const GET_ALL_NOTIFICATIONS_FAILURE = "  GET_ALL_NOTIFICATIONS_FAILURE";
export const GET_NOTIFICATIONS_BY_CUSTOMER_ID_REQUEST =
  "  GET_NOTIFICATIONS_BY_CUSTOMER_ID_REQUEST";
export const GET_NOTIFICATIONS_BY_CUSTOMER_ID_SUCCESS =
  "  GET_NOTIFICATIONS_BY_CUSTOMER_ID_SUCCESS";
export const GET_NOTIFICATIONS_BY_CUSTOMER_ID_FAILURE =
  "  GET_NOTIFICATIONS_BY_CUSTOMER_ID_FAILURE";
export const CREATE_NOTIFICATION_REQUEST = "  CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS = "  CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAILURE = "  CREATE_NOTIFICATION_FAILURE";
export const MARK_NOTIFICATION_AS_READ_REQUEST =
  "  MARK_NOTIFICATION_AS_READ_REQUEST";
export const MARK_NOTIFICATION_AS_READ_SUCCESS =
  "  MARK_NOTIFICATION_AS_READ_SUCCESS";
export const MARK_NOTIFICATION_AS_READ_FAILURE =
  "  MARK_NOTIFICATION_AS_READ_FAILURE";
export const DELETE_NOTIFICATION_REQUEST = "  DELETE_NOTIFICATION_REQUEST";
export const DELETE_NOTIFICATION_SUCCESS = "  DELETE_NOTIFICATION_SUCCESS";
export const DELETE_NOTIFICATION_FAILURE = "  DELETE_NOTIFICATION_FAILURE";
