export const CREATE_ONLINE_BANKING_ACCOUNT_REQUEST =
  "CREATE_ONLINE_BANKING_ACCOUNT_REQUEST";
export const CREATE_ONLINE_BANKING_ACCOUNT_SUCCESS =
  "  CREATE_ONLINE_BANKING_ACCOUNT_SUCCESS";
export const CREATE_ONLINE_BANKING_ACCOUNT_FAILURE =
  "  CREATE_ONLINE_BANKING_ACCOUNT_FAILURE";
export const GET_ONLINE_BANKING_ACCOUNT_BY_CUSTOMER_ID_REQUEST =
  "  GET_ONLINE_BANKING_ACCOUNT_BY_CUSTOMER_ID_REQUEST";
export const GET_ONLINE_BANKING_ACCOUNT_BY_CUSTOMER_ID_SUCCESS =
  "  GET_ONLINE_BANKING_ACCOUNT_BY_CUSTOMER_ID_SUCCESS";
export const GET_ONLINE_BANKING_ACCOUNT_BY_CUSTOMER_ID_FAILURE =
  "  GET_ONLINE_BANKING_ACCOUNT_BY_CUSTOMER_ID_FAILURE";
export const UPDATE_ONLINE_BANKING_ACCOUNT_REQUEST =
  "  UPDATE_ONLINE_BANKING_ACCOUNT_REQUEST";
export const UPDATE_ONLINE_BANKING_ACCOUNT_SUCCESS =
  "  UPDATE_ONLINE_BANKING_ACCOUNT_SUCCESS";
export const UPDATE_ONLINE_BANKING_ACCOUNT_FAILURE =
  "  UPDATE_ONLINE_BANKING_ACCOUNT_FAILURE";
export const DELETE_ONLINE_BANKING_ACCOUNT_REQUEST =
  "  DELETE_ONLINE_BANKING_ACCOUNT_REQUEST";
export const DELETE_ONLINE_BANKING_ACCOUNT_SUCCESS =
  "  DELETE_ONLINE_BANKING_ACCOUNT_SUCCESS";
export const DELETE_ONLINE_BANKING_ACCOUNT_FAILURE =
  "  DELETE_ONLINE_BANKING_ACCOUNT_FAILURE";
