export const GET_ALL_PAYMENT_GATEWAYS_REQUEST =
  " GET_ALL_PAYMENT_GATEWAYS_REQUEST";
export const GET_ALL_PAYMENT_GATEWAYS_SUCCESS =
  "  GET_ALL_PAYMENT_GATEWAYS_SUCCESS";
export const GET_ALL_PAYMENT_GATEWAYS_FAILURE =
  "  GET_ALL_PAYMENT_GATEWAYS_FAILURE";
export const GET_PAYMENT_GATEWAY_BY_ID_REQUEST =
  "  GET_PAYMENT_GATEWAY_BY_ID_REQUEST";
export const GET_PAYMENT_GATEWAY_BY_ID_SUCCESS =
  "  GET_PAYMENT_GATEWAY_BY_ID_SUCCESS";
export const GET_PAYMENT_GATEWAY_BY_ID_FAILURE =
  "  GET_PAYMENT_GATEWAY_BY_ID_FAILURE";
export const CREATE_PAYMENT_GATEWAY_REQUEST =
  "  CREATE_PAYMENT_GATEWAY_REQUEST";
export const CREATE_PAYMENT_GATEWAY_SUCCESS =
  "  CREATE_PAYMENT_GATEWAY_SUCCESS";
export const CREATE_PAYMENT_GATEWAY_FAILURE =
  "  CREATE_PAYMENT_GATEWAY_FAILURE";
export const UPDATE_PAYMENT_GATEWAY_REQUEST =
  "  UPDATE_PAYMENT_GATEWAY_REQUEST";
export const UPDATE_PAYMENT_GATEWAY_SUCCESS =
  "  UPDATE_PAYMENT_GATEWAY_SUCCESS";
export const UPDATE_PAYMENT_GATEWAY_FAILURE =
  "  UPDATE_PAYMENT_GATEWAY_FAILURE";
export const DELETE_PAYMENT_GATEWAY_REQUEST =
  "  DELETE_PAYMENT_GATEWAY_REQUEST";
export const DELETE_PAYMENT_GATEWAY_SUCCESS =
  "  DELETE_PAYMENT_GATEWAY_SUCCESS";
export const DELETE_PAYMENT_GATEWAY_FAILURE =
  "  DELETE_PAYMENT_GATEWAY_FAILURE";
