export const GENERATE_ACCOUNT_STATEMENTS_REQUEST =
  " GENERATE_ACCOUNT_STATEMENTS_REQUEST";
export const GENERATE_ACCOUNT_STATEMENTS_SUCCESS =
  "  GENERATE_ACCOUNT_STATEMENTS_SUCCESS";
export const GENERATE_ACCOUNT_STATEMENTS_FAILURE =
  "  GENERATE_ACCOUNT_STATEMENTS_FAILURE";
export const GENERATE_TRANSACTION_HISTORY_REQUEST =
  "  GENERATE_TRANSACTION_HISTORY_REQUEST";
export const GENERATE_TRANSACTION_HISTORY_SUCCESS =
  "  GENERATE_TRANSACTION_HISTORY_SUCCESS";
export const GENERATE_TRANSACTION_HISTORY_FAILURE =
  "  GENERATE_TRANSACTION_HISTORY_FAILURE";
export const GENERATE_CUSTOMER_ACTIVITY_REQUEST =
  "  GENERATE_CUSTOMER_ACTIVITY_REQUEST";
export const GENERATE_CUSTOMER_ACTIVITY_SUCCESS =
  "  GENERATE_CUSTOMER_ACTIVITY_SUCCESS";
export const GENERATE_CUSTOMER_ACTIVITY_FAILURE =
  "  GENERATE_CUSTOMER_ACTIVITY_FAILURE";
export const GENERATE_FINANCIAL_ANALYSIS_REQUEST =
  "  GENERATE_FINANCIAL_ANALYSIS_REQUEST";
export const GENERATE_FINANCIAL_ANALYSIS_SUCCESS =
  "  GENERATE_FINANCIAL_ANALYSIS_SUCCESS";
export const GENERATE_FINANCIAL_ANALYSIS_FAILURE =
  "  GENERATE_FINANCIAL_ANALYSIS_FAILURE";
