export const GET_ALL_THIRD_PARTY_SERVICES_REQUEST =
  "GET_ALL_THIRD_PARTY_SERVICES_REQUEST";
export const GET_ALL_THIRD_PARTY_SERVICES_SUCCESS =
  "  GET_ALL_THIRD_PARTY_SERVICES_SUCCESS";
export const GET_ALL_THIRD_PARTY_SERVICES_FAILURE =
  "  GET_ALL_THIRD_PARTY_SERVICES_FAILURE";
export const GET_THIRD_PARTY_SERVICE_BY_ID_REQUEST =
  "  GET_THIRD_PARTY_SERVICE_BY_ID_REQUEST";
export const GET_THIRD_PARTY_SERVICE_BY_ID_SUCCESS =
  "  GET_THIRD_PARTY_SERVICE_BY_ID_SUCCESS";
export const GET_THIRD_PARTY_SERVICE_BY_ID_FAILURE =
  "  GET_THIRD_PARTY_SERVICE_BY_ID_FAILURE";
export const CREATE_THIRD_PARTY_SERVICE_REQUEST =
  "  CREATE_THIRD_PARTY_SERVICE_REQUEST";
export const CREATE_THIRD_PARTY_SERVICE_SUCCESS =
  "  CREATE_THIRD_PARTY_SERVICE_SUCCESS";
export const CREATE_THIRD_PARTY_SERVICE_FAILURE =
  "  CREATE_THIRD_PARTY_SERVICE_FAILURE";
export const UPDATE_THIRD_PARTY_SERVICE_REQUEST =
  "  UPDATE_THIRD_PARTY_SERVICE_REQUEST";
export const UPDATE_THIRD_PARTY_SERVICE_SUCCESS =
  "  UPDATE_THIRD_PARTY_SERVICE_SUCCESS";
export const UPDATE_THIRD_PARTY_SERVICE_FAILURE =
  "  UPDATE_THIRD_PARTY_SERVICE_FAILURE";
export const DELETE_THIRD_PARTY_SERVICE_REQUEST =
  "  DELETE_THIRD_PARTY_SERVICE_REQUEST";
export const DELETE_THIRD_PARTY_SERVICE_SUCCESS =
  "  DELETE_THIRD_PARTY_SERVICE_SUCCESS";
export const DELETE_THIRD_PARTY_SERVICE_FAILURE =
  "  DELETE_THIRD_PARTY_SERVICE_FAILURE";
